### ISSUE TITLE
Receiving net::ERR_CONTENT_LENGTH_MISMATCH for method getAll

### ISSUE THREAD

**Issue by ohager** [gpedro34/BURST-NetX#2]
**Describe the bug**
When trying to load the page or hitting the following endpoint directly, I'm getting

GET https://watchdog.burst-alliance.org/api/getAll?from=scans&where=peer_id&value=33 net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

Even worse, the entire app hangs and stays with the loading icon only!

**To Reproduce**
1. Open the site, or call the endpoint in chrome/brave
2. Open Dev Tools
3. Wait until request concludes
4. See error in console tab

**Screenshots**

![image](https://user-images.githubusercontent.com/3920663/55795901-2f37d980-5a9f-11e9-8303-897668f4703b.png)
Brave/Chrome

![image](https://user-images.githubusercontent.com/3920663/55796110-8fc71680-5a9f-11e9-9de2-bb279895f096.png)
Firefox

**Expected behavior**
Loads data without error, and apps opens normally

**Desktop:**
 - OS: Ubuntu 18.04
 - Browser 
     - Chrome Version 72.0.3626.109 (Official Build) (64-bit)
     - Brave Version 0.59.35 Chromium: 72.0.3626.81 (Official Build) (64-bit), 
     - Firefox 65.0.1 (64-bit)

**Additional context**

**Comment by eagle275** [comment]
strange .. I have developer tools as part of mozilla firefox ... but on a regular start .. you dont encounter this get-request ... did you enter something specific into search ?

**Comment by gpedro34** [comment]
@eagle275 this was already fixed...
@ohager can you confirm if the error still persists? If so please reopen it 😉
Both Chrome and Firefox seem to be working fine for me... Closing for now

**Comment by ohager** [comment]
Could not reproduce anymore, although it stays a good time on loading...

![image](https://user-images.githubusercontent.com/3920663/56916784-2760c900-6a90-11e9-836f-d0a484a661d5.png)
